name: typing_game
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/word_lists/
    - assets/fonts/

  fonts:
      - family: NotoSansJP
        fonts:
          - asset: assets/fonts/NotoSansJP-Black.otf
            weight: 900
          - asset: assets/fonts/NotoSansJP-Bold.otf
            weight: 700
          - asset: assets/fonts/NotoSansJP-Light.otf
            weight: 300
          - asset: assets/fonts/NotoSansJP-Medium.otf
            weight: 500
          - asset: assets/fonts/NotoSansJP-Regular.otf
            weight: 400
          - asset: assets/fonts/NotoSansJP-Thin.otf
            weight: 100
      - family: OunenMouhitsu
        fonts:
          - asset: assets/fonts/Ounen-mouhitsu.otf
